### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by UserXGnu** [lampiaosec/virgulino#25]
Well guys, github give us the nice feature of the possibility to create a wiki to any project.
So, what do you, guys, think about it? Let's build Virgulino's wiki?

**Comment by n3k00n3** [comment]
I think that is very interesting. +1!

**Comment by gjuniioor** [comment]
So cool!!

What you think about https://github.com/lampiaosec/virgulino/wiki ?

Please, coders: if you think it is interesting talk about the code, start a new page :+1:

**Comment by elfotux** [comment]
Cool. I will do it!

**Comment by UserXGnu** [comment]
once that it's not something to be done and we all know that everyone of us read this, I'm closing this issue.
