### ISSUE TITLE
ADFGVX

### ISSUE THREAD

**Issue by n3k00n3** [lampiaosec/virgulino#29]
Hey what do you think about it?
https://pt.wikipedia.org/wiki/Cifra_ADFGVX

**Comment by UserXGnu** [comment]
I don't think that it's hard to do but, there's somethings that should be considered. How to deliver the key? Should the key be auto-generated or provided by the end-user? Such a large key could be forgothen by the end-user if he chooses it by his own. We need to consider these things...

**Comment by n3k00n3** [comment]
Hey @UserXGnu Let's talk about it, and think how to create it, all right? We need to decide a milestone  to finish in both version.

**Comment by UserXGnu** [comment]
alright, but actually, we need to define the versioning stuff. But yeah, let's talk about this.
