### ISSUE TITLE
header files

### ISSUE THREAD

**Issue by UserXGnu** [lampiaosec/virgulino#34]
Guys, as we all know, our project is growing fast, by now, and I think that it's time to separate the code to spread responsibilities into several files (header files) on ruby version. It will help us maintain the project and turn it into an API so that we can allow another developers to use virgulino's API to build their own projects.

What do you, guys, think about this?

@n3k00n3 @gjuniioor @elfotux @lucascudo 

P.S: Please, take a look at https://github.com/lampiaosec/virgulino/tree/master/src 

If we decide to do this, please, fallow the same pattern as the C version on header names and responsibilities.

**Comment by elfotux** [comment]
I was thinking about it and add the python language as well.
Very good

**Comment by gjuniioor** [comment]
@elfotux Isso?

**Comment by UserXGnu** [comment]
Elfo, I think that you misunderstood! It's hard enough to maintain Virgulino in two languages, we can't maintain it with a new one! So, what I said above was about the project engine and architecture not about build the whole thing again with another language such python or any other...

**Comment by elfotux** [comment]
Ok man, I understand your preocupation.
Let's go on 2 languagens.
Thank you.

**Comment by gjuniioor** [comment]
Really! I think that we need this. All code in one file is not a good practice.

**Comment by UserXGnu** [comment]
As we all agreed, I'll marking this issue as LGTM.

**Comment by n3k00n3** [comment]
Tomorrow we'll close this issue.

**Comment by gjuniioor** [comment]
@n3k00n3 's doing it, right?

**Comment by n3k00n3** [comment]
Yes, I am doing, but we can close this issue and I put this task in #41. What you think?

**Comment by gjuniioor** [comment]
The inverse was made, so, let's go!

**Comment by n3k00n3** [comment]
Header files done, all right? @gjuniioor

**Comment by UserXGnu** [comment]
As we are building the whole thing from the scratch with a new project design, this issue no longer fits to the problem once that we already have issues in progress to solve this. I'm closing it.
