### ISSUE TITLE
pigpen cypher

### ISSUE THREAD

**Issue by n3k00n3** [lampiaosec/virgulino#39]
Since we want to learn about the largest type of encryption possible, Achi some more for us to play and see how to implement :)

Pigpen cypher.

What do you think?

**Comment by gjuniioor** [comment]
Nice. Have a caracteres table for this?

**Comment by UserXGnu** [comment]
no, we would need to build our own

**Comment by n3k00n3** [comment]
did u see this https://codegolf.stackexchange.com/questions/37658/pigpen-cipher-encryption ?

**Comment by UserXGnu** [comment]
as you can see, it's almost impractical...

**Comment by n3k00n3** [comment]
I agree :)
