### ISSUE TITLE
Crypto type

### ISSUE THREAD

**Issue by UserXGnu** [lampiaosec/virgulino#40]
As I said on telegram, I have created a simple mathematical function to turn characters into pseudo-randomized numbers so that characters from the same text could be never repeated on the ciphered result. 

Function: f(x) = x + 26 * K  ←→  31 < x < 127 & K € |N  (ascii table)

What do you, guys, think about this?

**Comment by n3k00n3** [comment]
Go for it!

**Comment by UserXGnu** [comment]
Alright then, I'll start it as soon as I can...setting a milestone.
