### ISSUE TITLE
Man Page

### ISSUE THREAD

**Issue by n3k00n3** [lampiaosec/virgulino#43]
# Create man page to help end users.

* how to use all forms
* all parameters
* cypher types
* files supported

**Comment by elfotux** [comment]
I make man page.

**Comment by elfotux** [comment]
Starting...

**Comment by UserXGnu** [comment]
Please, create a milestone and set it to this issue ok?

**Comment by elfotux** [comment]
Guys, I finished the man page. I need information for write in the man page.
Follow bellow a example about the information what I need to finish this issue

NAME
    The name of the command or function, followed by a one-line description of what it does.
SYNOPSIS
    In the case of a command, you get a formal description of how to run it and what command line options it takes.
DESCRIPTION
    A textual description of the functioning of the command or function.
EXAMPLES
    Some examples of common usage.
SEE ALSO
    A list of related commands or functions.
BUGS
    List known bugs.
AUTHOR
   Specify your contact information.
COPYRIGHT
    Specify your copyright information.

**Comment by UserXGnu** [comment]
Elfo, please, take a look at some manpage's from common commands like ls, cp, vim, nano and so on. It will give you the mindset you need to keep going.

kind regards

**Comment by UserXGnu** [comment]
Elfo, you need to create a now milestone for your issue, do not use another issue's milestone. Create a new one and set it to your issue and pr.

**Comment by n3k00n3** [comment]
@elfotux Your time expired, and yesterday, i said with Gjr to do this task. All right?

**Comment by gjuniioor** [comment]
* [ ] c/man page 1
* [ ] c/man page 3
* [ ] ruby/man page 1

**Comment by UserXGnu** [comment]
Manpage is not an issue, it's a process
