### ISSUE TITLE
Code design

### ISSUE THREAD

**Issue by UserXGnu** [lampiaosec/virgulino#44]
The C version of virgulino needs some design improvement in the way that it can handle with future modifications and new features without large effort.

**Comment by UserXGnu** [comment]
To day I changed project design starting by cypher.h and cypher_utils.h (renamed files cipher.h cipher_utils.h). I changed the functions signatures to allow a better flexibility to developers in the future.

Take a look at 
https://github.com/lampiaosec/virgulino/commit/912624034edb83d272131438eb0fcfe053e293dd

**Comment by UserXGnu** [comment]
Keep tracking - 

I'm working on the new project design and it's harder than I thought it would be but I'm pushing forward. Anyway if any of you want to follow the progress here follows the commit link, take a look:
https://github.com/lampiaosec/virgulino/commit/55dc2b9d9f5324f5c74c3ff8107ec56327a6fc8c

**Comment by UserXGnu** [comment]
Hey guys,
About the new code design. To day I've done a lot of progress, vigenere and ceasar as well as steg stuff are now available and working very well. I need to fix somethings like memory leaking, and auto-generate key functions is still buggy. I'll keep working on that tonight.

Take a look: https://github.com/lampiaosec/virgulino/commit/14209094ed4d9e8be18693024a9359f345e928df

**Comment by n3k00n3** [comment]
Congratz! \o

**Comment by UserXGnu** [comment]
Guys, I'm opening the PR because the code is pretty usable without large issues. But it's not ready yet so please don't merge it!

**Comment by UserXGnu** [comment]
Guys, I have finished virgulino's C version new project design. It's all done. PR has been made, take a look #48

**Comment by UserXGnu** [comment]
Once that I have finished this job, I'm closing this issue. If any of you have anything to comment, please, comment on PR. (#48).
