### ISSUE TITLE
C-XCrypto

### ISSUE THREAD

**Issue by UserXGnu** [lampiaosec/virgulino#50]
As I said on telegram, I have created a simple mathematical function to turn characters into pseudo-randomized numbers so that characters from the same text could be never repeated on the ciphered result.

Function: f(x) = x + 26 * K ←→ 31 < x < 127 & K € |N (ascii table)

What do you, guys, think about this?

**Comment by n3k00n3** [comment]
Hey dude, could you explain in details?

**Comment by UserXGnu** [comment]
f(x) = x + 94 * K 
x must be greater or equal to 32 (space ascii number) and lower or equal to 126 (~ ascii number).
K is a randomic number. 94 = 126 - 32 (126 higher printable character from the ascii table, 32 lower printable character from the ascii table. Result: 94 (number of characters that can be used).

**Comment by UserXGnu** [comment]
As we all agreed, I'm removing this issue once that it's not required anymore
