### ISSUE TITLE
Navajo code

### ISSUE THREAD

**Issue by n3k00n3** [lampiaosec/virgulino#58]
This is not a kind of cypher, its a kind of code.
Navajo code was used by EUA when fought with military japaneses. 
They used this because Navajo was a unknow language, only a group of people knew how to talk, for this reason, was a great code, better than enigma code. 

Now is knonw, but i think that we can use some parts of this in virgulino.

What do you think about it?

**Comment by n3k00n3** [comment]
https://www.cia.gov/news-information/featured-story-archive/2008-featured-story-archive/navajo-code-talkers/

**Comment by n3k00n3** [comment]
novajo_encrypt done! ;)

**Comment by n3k00n3** [comment]
Hey guys, answer please!

**Comment by gjuniioor** [comment]
I think that is a good idea! Really! :)

**Comment by UserXGnu** [comment]
Not applicable to the project goal.
