### ISSUE TITLE
Morse code

### ISSUE THREAD

**Issue by n3k00n3** [lampiaosec/virgulino#59]
hey guys, what do you think about morse code?
Is it interesting for our project?

**Comment by gjuniioor** [comment]
Maybe, using for each letter or anyway like the first release (binary)?

**Comment by n3k00n3** [comment]
The idea would be to put in morse code, after that hide at the end of the text as spaces and tabs

**Comment by n3k00n3** [comment]
I'm close this issue, 'Cause yesterday we decided that's not interesting for our project.
