### ISSUE TITLE
Steg param

### ISSUE THREAD

**Issue by gjuniioor** [lampiaosec/virgulino#60]
Heya!!

What do you think about change how virgulino uses steg param (`-s`)?

For now, the project uses `-s` to save a file. It does'nt matter if the `-f` was passed it needs to set `-s` param to work too:

```
$ ./virgulino -e -c 12 -m "oxente" -f test.txt -s shablau.png # work
$ ./virgulino -e -c 12 -m "oxente" -f test.txt # doesn't work
```

I think that it is better to use `-s` to set the original file to use in the steg process. Something like this:

```
$ ./virgulino -e -c 12 -m "oxente" -f end_file.png -s original_image.png
```

**Comment by UserXGnu** [comment]
I have some stuff to do but I'll set a deadline as soon as I can.

**Comment by UserXGnu** [comment]
Due to changes on the project, this issue must be fixed again.

**Comment by UserXGnu** [comment]
Virgulino had a large amount of changes this last two weeks, this issue is not necessary anymore.
