### ISSUE TITLE
Gh-Page and Documentation

### ISSUE THREAD

**Issue by gjuniioor** [lampiaosec/virgulino#61]
Heya!

Generally, projects use README.md OR Wiki OR Github Pages to have a documentation. We have this three ways. Of course, was redused - we "remove" the README.md to use wiki.

Well, today I propose "remove" [Github Page](https://lampiaosec.github.io/virgulino) too for have focus on wiki. Don't just remove the branch `gh-page` but make somethink like this: 

* https://github.com/lampiaosec/virgulino/blob/master/README.md

**Comment by UserXGnu** [comment]
agreed.
