### ISSUE TITLE
All code in one branch

### ISSUE THREAD

**Issue by gjuniioor** [lampiaosec/virgulino#65]
Virgulino has two versions in two differents branches.

I think that is better use one branch to all code. Yep, mantain C and ruby version in branch `master`.

As we decided before, here go two ways that this can do:

* Subdirectories:

```
./
  - c/
  - doc/
  - ruby/
  - LICENSE
  - Makefile
  - README.md
```

* Use git feature: submodules

What do you guys think about this?

**Comment by n3k00n3** [comment]
That's great!

**Comment by UserXGnu** [comment]
Sadly, the submodule process isn't what we thought it is....every submodule is actually another repository so we would need to create another two repositories...it's not practical .. I'm closing this issue once that it would be more trouble than what it's now.

**Comment by gjuniioor** [comment]
So, my suggestion is wait to merge this two PRs (#49 && #56) or another that appear and after this, go to merge using the first scheme: directories.

Right?

**Comment by UserXGnu** [comment]
Issue no longer required.
