### ISSUE TITLE
RSA 

### ISSUE THREAD

**Issue by n3k00n3** [lampiaosec/virgulino#69]
I am doing the rsa cypher to use public keys and privates.

it's simple, but i'm seeing how to get the numbers from public keys.

**Comment by n3k00n3** [comment]
I'll finish and make a PR for our second version :)

**Comment by UserXGnu** [comment]
you can't do this dude.
the whole project is about to change  changed. We need to handle the issues yet open.

**Comment by n3k00n3** [comment]
I got i!
