### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by n3k00n3** [lampiaosec/virgulino#70]
Hi there!

So, we are going to version 2 :)
I thought that I can create a new feature for this version, beyond the RSA and DES..

Actually we can to encrypt and to decrypt.

Why not to do attacks when we do not know the key to a cipher text?
we can do a brute force for Caesar cipher for example and a dictionary attack for Vigenère.

for example:

` ./virgulino -a(attack) --caesar k all(here we have 26 tries) -m <message> or -f <file>`

`./virgulino -a --vigenere -k (dictionary file) -m <message> or -f <file>`

What do you think about it?

**Comment by UserXGnu** [comment]
It's all good, however as we decided before, there's no need to use -k switch to pass the key so...
The same thing to -m. Passing message as parameter is inpractical once that the encrypted message will be hidden into a file.

`./viruglino [-a] [-c -v] <KEY/ALL/WORDLIST> [-f] <filepath>`

so "filepath" would be used as a source file with the hidden & encrypted message that virgulino would be smart enough to locate and extract by itself.

**Comment by n3k00n3** [comment]
We will need to use -k all cause is a caesar cipher. we can use -w to use a dictionary.

When the file was created by virgulino, the attacker must to use -s <txt/image>to take out the message before break it.

**Comment by UserXGnu** [comment]
Due to changes on the project needs this issue is now closed.
